---
- hosts: "default:localhost"
  connection: "local"
  become: yes
  become_user: "root"
  vars_files:
  - "config.yml"

  roles:
  # update the system to the latest packages
  - role: "system-update"

  # local user preferences
  - role: "local"

  # local get my public ip
  - role: "public-ip"

  # https://galaxy.ansible.com/geerlingguy/docker
  - role: "geerlingguy.docker"
    docker_users:
    - "vagrant"
    when: install_docker | default(false)

  # https://galaxy.ansible.com/geerlingguy/postgresql
  - role: "geerlingguy.postgresql"
    postgresql_users:
    - name: "vagrant"
      role_attr_flags: "SUPERUSER"
    when: install_pg | default(false)

  # https://galaxy.ansible.com/geerlingguy/nodejs
  - role: "geerlingguy.nodejs"
    nodejs_version: "10.x"
    when: install_node | default(false)

  # https://galaxy.ansible.com/avanov/pyenv
  - role: "avanov.pyenv"
    user: "vagrant"
    version: "3.7.7"
    pyenv_env: "user"
    pyenv_owner: "{{ user }}"
    pyenv_path: "/home/{{ user }}/.pyenv"
    pyenv_virtualenvs: []
    pyenv_python_versions:
    - "{{ version }}"
    pyenv_global: "{{ version }}"
    pyenv_enable_autocompletion: yes
    pyenv_update_git_install: yes
    when: install_pyenv | default(false)

  # https://galaxy.ansible.com/rvm/ruby
  - role: "rvm.ruby"
    rvm1_rubies:
    - "2.6.5"
    rvm1_user: "vagrant"
    when: install_rvm | default(false)

  # https://galaxy.ansible.com/gantsign/golang
  - role: "gantsign.golang"
    golang_version: "1.12.17"
    golang_gopath: "${HOME}/go"
    when: install_go | default(false)

  # https://galaxy.ansible.com/naftulikay/rust-dev
  - role: "naftulikay.rust-dev"
    rust_user: "vagrant"
    rust_version: "1.42.0"
    when: install_rust | default(false)

  # https://galaxy.ansible.com/dokku_bot/ansible_dokku
  - role: "dokku_bot.ansible_dokku"
    dokku_daemon_install: false
    #dokku_version: "0.20.4"
    dokku_version: "0.17.0"
    sshcommand_version: "0.11.0"
    dokku_key_file: "/home/vagrant/.ssh/id_ed25519.pub"
    #dokku_hostname: "127.0.0.1.nip.io"
    dokku_hostname: "{{ nip_domain }}"
    dokku_plugins:
    - name: postgres
      url: https://github.com/dokku/dokku-postgres.git
    - name: redis
      url: https://github.com/dokku/dokku-redis.git
    - name: letsencrypt
      url: https://github.com/dokku/dokku-letsencrypt.git
    dokku_web_config: false
    dokku_vhost_enable: true
    when: install_dokku | default(false)

  # Dokku customizations
  - role: "dokku-sample-app"
    enable_https: "{{ dokku_enable_https | default(false) }}"
    become: yes
    become_user: "vagrant"
    when: (install_dokku and dokku_install_sample) | default(false)
