- name: "geerlingguy.nodejs"
  version: "5.0.0"
- name: "avanov.pyenv"
  version: "1.0.0"
- name: "rvm.ruby"
  version: "v2.1.2"
- name: "geerlingguy.postgresql"
  version: "1.4.5"
- name: "geerlingguy.docker"
  version: "2.5.2"
- name: "gantsign.golang"
  version: "2.1.4"
