- name: "geerlingguy.nodejs"
  version: "5.0.0"
- name: "avanov.pyenv"
  version: "1.1.0"
- name: "rvm.ruby"
  version: "v2.1.2"
- name: "geerlingguy.postgresql"
  version: "1.4.6"
- name: "geerlingguy.docker"
  version: "2.5.2"
- name: "gantsign.golang"
  version: "2.1.9"
- name: "naftulikay.rust-dev"
  version: "v3.1.0"
