- name: "geerlingguy.nodejs"
  version: "5.1.1"
- name: "avanov.pyenv"
  version: "1.1.0"
- name: "rvm.ruby"
  version: "v2.1.2"
- name: "geerlingguy.postgresql"
  version: "1.4.7"
- name: "geerlingguy.docker"
  version: "2.7.0"
- name: "gantsign.golang"
  version: "2.3.1"
- name: "naftulikay.rust-dev"
  version: "v3.2.0"
