---
- name: "add packages"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: "present"
  with_items:
  - "git"
  - "vim"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "remove packages"
  apt:
    pkg: item
    purge: yes
    state: "absent"
    autoclean: yes
    autoremove: yes
  with_items:
  - "vim-tiny"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# TODO Red Hat, etc.
