---
- name: "add packages"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: "present"
  with_items:
  - "git"
  - "gpg"
  - "make"
  - "vim"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "remove packages"
  apt:
    pkg: item
    purge: yes
    state: "absent"
    autoclean: yes
    autoremove: yes
  with_items:
  - "vim-tiny"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# TODO Red Hat, etc.


- name: "local directories"
  file:
    path: "{{ item }}"
    owner: "vagrant"
    group: "vagrant"
    mode: "0755"
    state: directory
  with_items:
  - "{{ vagrant_home }}/.local/bin"
  - "{{ vagrant_home }}/.local/src"

- name: "local scripts"
  copy:
    src: "{{ item }}"
    dest: "{{ vagrant_home }}/.local/bin/{{ item }}"
    owner: "vagrant"
    group: "vagrant"
    mode: "0755"
  with_items:
  - "b.sh"
  - "t.sh"
